sudo: required
services:
    - docker
before_install:
    - curl https://sdk.cloud.google.com | bash  > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in multi-k8s-262503-57ad30b114b7.json.enc -out multi-k8s-262503-57ad30b114b7.json -d